-- MySQL Script generated by MySQL Workbench
-- Sat Jul  4 23:37:28 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Imovel
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Imovel` ;

-- -----------------------------------------------------
-- Schema Imovel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Imovel` DEFAULT CHARACTER SET utf8 ;
USE `Imovel` ;

-- -----------------------------------------------------
-- Table `Imovel`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Imovel`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `Imovel`.`Categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Imovel`.`Imovel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Imovel`.`Imovel` ;

CREATE TABLE IF NOT EXISTS `Imovel`.`Imovel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(45) NOT NULL,
  `Nome_Rua` VARCHAR(45) NOT NULL,
  `Bairro` VARCHAR(45) NOT NULL,
  `Cidade` VARCHAR(45) NOT NULL,
  `Preco_Venda` DECIMAL(9,2) NOT NULL,
  `Categoria_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Categoria_id`),
  INDEX `fk_Imovel_Categoria_idx` (`Categoria_id` ASC),
  CONSTRAINT `fk_Imovel_Categoria`
    FOREIGN KEY (`Categoria_id`)
    REFERENCES `Imovel`.`Categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
